
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from io import BytesIO

def export_to_excel(data, cost_data=None, filename="dairy_yield.xlsx"):
    """Exports a list of dictionaries (results) and optional cost data to an Excel file."""
    if not data:
        return None

    output = BytesIO()
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
        # Write yield results
        df_yield = pd.DataFrame(data)
        df_yield.to_excel(writer, index=False, sheet_name='Yield Results')

        # Write cost data if provided
        if cost_data:
            cost_items = [
                {"Metric": "Total Input Cost", "Value": f"${cost_data['total_input_cost']:.2f}"},
                {"Metric": "Total Output Value", "Value": f"${cost_data['total_output_value']:.2f}"},
                {"Metric": "Profit/Loss", "Value": f"${cost_data['profit_loss']:.2f}"}
            ]
            df_costs = pd.DataFrame(cost_items)
            df_costs.to_excel(writer, index=False, sheet_name='Cost Analysis')

    output.seek(0)
    return output.getvalue()

def export_to_pdf(input_product, input_quantity, input_unit, results, cost_data=None, filename="dairy_yield.pdf"):
    """Exports calculation results and optional cost data to a PDF file."""
    if not results:
        return None

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph("Dairy Product Yield Report", styles['h1']))
    story.append(Spacer(1, 0.2 * 100))

    # Input Details
    story.append(Paragraph(f"<b>Input Product:</b> {input_product}", styles['Normal']))
    story.append(Paragraph(f"<b>Input Quantity:</b> {input_quantity:.2f} {input_unit}", styles['Normal']))
    story.append(Spacer(1, 0.2 * 100))

    # Results Table
    table_data = [['Product', 'Quantity', 'Unit']]
    for item in results:
        table_data.append([item['Product'], item['Quantity'], item['Unit']])

    table = Table(table_data)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(table)
    story.append(Spacer(1, 0.4 * 100))

    # Cost Analysis if provided
    if cost_data:
        story.append(Paragraph("<b>Cost Analysis:</b>", styles['h2']))
        story.append(Paragraph(f"<b>Total Input Cost:</b> ${cost_data['total_input_cost']:.2f}", styles['Normal']))
        story.append(Paragraph(f"<b>Total Output Value:</b> ${cost_data['total_output_value']:.2f}", styles['Normal']))
        story.append(Paragraph(f"<b>Profit/Loss:</b> ${cost_data['profit_loss']:.2f}", styles['Normal']))
        story.append(Spacer(1, 0.4 * 100))

    story.append(Paragraph("Report generated by Dairy Product Yield Calculator.", styles['Small']))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
